name: Python Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: 3.10.11

permissions:
  contents: write
jobs:

  train_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user poetry
    - name: Run unit tests Packages Extraction
      working-directory: train/extraction
      run: |
        poetry install
        poetry run coverage run -m unittest tests.extraction_tests
        poetry run coverage report
